M48
; DRILL file {KiCad (6.0.6)} date Tue Oct  4 12:54:13 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-04T12:54:13+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1570
%
G90
G05
T1
X3.85Y-3.7
X4.25Y-3.7
X4.6Y-3.7
X5.0Y-3.7
X5.35Y-3.7
X5.75Y-3.7
X6.1Y-3.7
X6.5Y-3.7
X6.85Y-3.7
X7.25Y-3.7
X7.6Y-3.7
X8.0Y-3.7
T2
X4.05Y-3.7
X4.8Y-3.7
X5.55Y-3.7
X6.3Y-3.7
X7.05Y-3.7
X7.8Y-3.7
T0
M30
